### ISSUE TITLE
Example using babel-plugin-istanbul

### ISSUE THREAD

**Issue by michaelBenin** [SBoudrias/gulp-istanbul#113]
Is this library compatible with https://github.com/istanbuljs/babel-plugin-istanbul#integrations? 

If so, I think an example would be valuable. 

Thank you!

**Comment by SBoudrias** [comment]
@michaelBenin If you're using babel to produce instrumented code, then you probably don't need this plugin.

I would assume you could theoretically use it to produce the reports and enforce thresholds, but there would be easier way to handle that.
