### ISSUE TITLE
Node 7 istanbul 1.1.0-alpha.1

### ISSUE THREAD

**Issue by ninox92** [SBoudrias/gulp-istanbul#117]
Is there a version coming where I can use the Async Await functionality?
There is a istanbul 1.1.0-alpha.1 package which supports this. I would like it to use it in combination with Gulp

**Comment by SBoudrias** [comment]
https://github.com/SBoudrias/gulp-istanbul/issues/116

**Comment by ninox92** [comment]
I'm not using, and willing to use a instrumenter. Then I'll have to wait for the official release.
Thanks for the reply.
