### ISSUE TITLE
Migrate from istanbul to nyc

### ISSUE THREAD

**Issue by cowwoc** [SBoudrias/gulp-istanbul#141]
When installing the module I get this warning:

```
warning gulp-istanbul > istanbul@0.4.5: This module is no longer maintained, try this instead:
  npm i nyc
Visit https://istanbul.js.org/integrations for other alternatives.
```

**Comment by SBoudrias** [comment]
Indeed, the tools changed since I've created this plugin. Feel free to use something else for coverage.

This library was made for Istanbul and gulp. I do not plan to update to anything else.
