### ISSUE TITLE
task completion callback called too many times

### ISSUE THREAD

**Issue by chmontgomery** [SBoudrias/gulp-istanbul#22]
When trying the [basic example from the readme](https://github.com/SBoudrias/gulp-istanbul#example), I'm getting the following error:

```
[15:16:29] 'test' errored after 1.4 s task completion callback called too many times
```

I assume this is related to this new feature of orchestrator? https://github.com/orchestrator/orchestrator/issues/10 plus that you're also calling end within the plugin?: https://github.com/SBoudrias/gulp-istanbul/blob/master/index.js#L79

```
[15:16:29] Local version 3.8.2
```

**Comment by muhammadghazali** [comment]
> If you take in the done callback and you return the stream, gulp doesn't
> know if it should consider the task done when you call the callback or when
> the stream ends. This error message clues you into that ambiguity in your
> code.

I was ran into the same error and @robrich was right.
