### ISSUE TITLE
Support istanbul harmony in a separate branch

### ISSUE THREAD

**Issue by EricMCornelius** [SBoudrias/gulp-istanbul#30]
I'd like to request keeping a harmony branch tracking the same in istanbul.  As of right now, anything using ES6 syntax can't be used with this module.

As an aside, this looks like a pain point for npm in general, as you need
gulp-istanbul#harmony -> istanbul#harmony -> esprima#harmony

I've made the one-line change to package.json in my fork - but then realized I can't request a new upstream branch be created via pull-request

https://github.com/EricMCornelius/gulp-istanbul

**Comment by jakecraige** [comment]
Any update on this? Would be great to be able to use istanbul with 6to5. I can't actually get any coverage working with it unfortunately..

**Comment by BobbyKostadinov** [comment]
Istanbul support different branches for each release - https://github.com/fengmk2/istanbul/tree/harmony-0.3.x

I am happy to do a PR for updating this on the harmony branch here, but perhaps their structure can be copied so gulp-istanbul has a "harmony-0.3.x" branch as well ?

**Comment by cgmartin** [comment]
The `harmony` branch is somewhat behind master in terms of features (namely `includeUntested`). Any chance this branch could be brought up to speed? I'm using this for a koa project. Much thanks

**Comment by SBoudrias** [comment]
See the new way to specify custom Instrumenter https://github.com/SBoudrias/gulp-istanbul#instrumenter

This is the way forward with ES6. Maintaining two branches of the same small project is too hard.

**Comment by cgmartin** [comment]
Thanks @SBoudrias for the quick reply, that works perfectly. I'm new to ES6 and didn't realize isparta was the thing to use. Thanks for helping me connect the dots.

Here's an example gulpfile in case it helps someone: https://gist.github.com/cgmartin/599fefffd6baa161c615
