### ISSUE TITLE
100% Coverage of nothing: app files not passing through to istanbul?

### ISSUE THREAD

**Issue by atomantic** [SBoudrias/gulp-istanbul#37]
```
gulp.task('test', function (cb) {
    gulp.src(['./*.js'])
      .pipe(istanbul()) // Covering files
      .on('finish', function () {
        gulp.src(['test/*.js'])
        .pipe(lab('-v -C -l -m 0'))
        .pipe(istanbul.writeReports()) // Creating the reports after tests runned
        .on('end', cb);
      });
});
```

results in this:

```
----------|-----------|-----------|-----------|-----------|
File      |   % Stmts |% Branches |   % Funcs |   % Lines |
----------|-----------|-----------|-----------|-----------|
----------|-----------|-----------|-----------|-----------|
All files |       100 |       100 |       100 |       100 |
----------|-----------|-----------|-----------|-----------|


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
```

The output lcov.info is an empty file.
coverage-final.json contains and empty `{}`

**Comment by tandrewnichols** [comment]
I was also seeing this result (100% coverage with 0s reported for everything), and it was because I was using `gulp-spawn-mocha` instead of `gulp-mocha` because I was having test pollution across multiple test suites. I don't have test pollution now, but because the tests run in a separate process, they don't get the instrumented code from `hookRequire`. Is there any way around this? I found this related issue on istanbul that sketches out an approach to covering child processes, but it seems very manual: https://github.com/gotwarlost/istanbul/issues/97

**Comment by SBoudrias** [comment]
@tandrewnichols Well, you need the covered source to run and get the results after. So just setup your code like the browser workflow.

**Comment by tandrewnichols** [comment]
Right, but you also have to require the right code, which either means wrapping require with something that determines where to load it from (based on process.env or something) or _always_ using relative paths. It does work, and I've done it before, but it's slightly more error-prone than testing for the browser.

**Comment by SBoudrias** [comment]
The only other solution I see is you could do the instrumentation phase inside your spawned process.

**Comment by BeOleg** [comment]
42 is the answer to all questions )

**Comment by tandrewnichols** [comment]
I ended up including _both_ gulp-spawn-mocha and gulp-mocha in my test suite. I use gulp-spawn-mocha for integration tests and for unit tests not run under coverage, and I use gulp-mocha for running unit tests under coverage. This actually works quite well, as they both have the same method signature, so I just swap the "require" and leave everything else the same.

**Comment by Pyo25** [comment]
For those who arrive here from a search engine, this problem also appears when upgrading `gulp-mocha` to v4. (issue is explained here: https://github.com/SBoudrias/gulp-istanbul/issues/115)

In this case, the solution is to use `gulp-mocha` v3 or to directly use mocha & istanbul CLI (as mentioned in the issue).

**Comment by zgwenwen** [comment]
I am still having this issue when I just Hapi Lab, do I need to edit the package.json file to fix this?
