### ISSUE TITLE
Files required before instrumentation are loaded from require.cache

### ISSUE THREAD

**Issue by jpbackman** [SBoudrias/gulp-istanbul#42]
We are testing our modules with gulp-istanbul, but in our gulpfile we require() these modules, as some of our gulp tasks use them. This causes require to cache the files before they are instrumented by istanbul, so when the tests require them, the uninstrumented versions are returned from require.cache.

I'm not sure if this is exactly a gulp-istanbul issue.

As a workaround we do:

```
var through = require('through2')

gulp.task('test', function(cb) {
  gulp.src(['src/**/*.js'])
    .pipe(through.obj(function(file, enc, cb) {  // <-- workaround
      delete require.cache[file.path];
      cb(undefined, file);
    }))
    .pipe(istanbul({ includeUntested: true }))
    .on('finish', function() {
      gulp.src(['test/**/*.js'])
        .pipe(mocha())
        .pipe(istanbul.writeReports())
        .on('end', cb);
    });
});
```

**Comment by elkorep** [comment]
I'm getting "istanbul is not a function" when doing `.pipe(istanbul({ includedUntested: true })`
