### ISSUE TITLE
Enhance coverage variable with trace info?

### ISSUE THREAD

**Issue by robatron** [SBoudrias/gulp-istanbul#46]
I know this is probably a question for the [Istanbul](https://github.com/gotwarlost/istanbul/) project, but I thought I'd start by asking y'all first:

How might one go about enhancing the coverage variable's data structure with trace info, i.e., information about the calling statement? Such information would be useful to analyze the the test code itself.

I notice the coverage variable keeps call counts of statements, branches, and functions, e.g., 

```js
{ 
    // File path
    path: 'foo.js',
    
    // Execution counts for statements, branches, and functions of `foo.js`
    s:{ 
        '1': 2, // Statement "1" was called 2 times
        '2': 1, // Statement "2" was called 1 time
        ...
    },
    b: { ... },
    f: { ... },
    
    // Content of statements, branches, and functions of `foo.js`
    statementMap:   { ... },
    branchMap:      { ... }
    fnMap:          { ... },
}
```

But it would be nice if, instead of simple call counts, the coverage variable contained trace info of each call, e.g., 

```js
{ 
    path: 'foo.js',
    s:{ 
    
        // Call "1" was called twice, the length of `s[ '1' ]`
        '1': [
        
            // Call "1" was called by `foo-spec.js`, line 35, column 7
            {
                path: 'foo-spec.js',
                line: '35',
                col:  '7'
            },
            
            // Call "2" was called by `bar-spec.js`, line 7, column 10
            {
                path: 'bar-spec.js',
                line: '7',
                col:  '10'
            }
        ], 
        
        // Call "2" was called once
        '2': [ { ... } ],
        ...
    },
    b: { ... },
    f: { ... },

    ...
}
```

Seems like I may need to make a custom [Instrumenter](https://github.com/gotwarlost/istanbul/blob/master/lib/instrumenter.js). What do you think? Can you think of a simpler way of achieving this?

Thanks!

**Comment by SBoudrias** [comment]
Going through old issues, this is effectively an Instabul/custom instrumenter question.
