### ISSUE TITLE
Gulp 4 compatibility

### ISSUE THREAD

**Issue by ilanbiala** [SBoudrias/gulp-istanbul#48]
Is gulp-istanbul currently compatible with Gulp 4.0?

**Comment by SBoudrias** [comment]
Haven't tested it out.

Feel free to test it and report any issues!

**Comment by ilanbiala** [comment]
Piping to `istanbul()` (`.pipe(istanbul())`) kills the pipe it seems.

**Comment by SBoudrias** [comment]
And that's not happening in 0.3? Because `istanbul` is correctly passing through the files it receive.

**Comment by ilanbiala** [comment]
```
gulp.src([
      'app/**/*.js',
      'config/**/*.js',
      'public/modules/**/*.js'
    ])
    .pipe(istanbul())
    .on('finish', function() {
      gulp.src('./test/**/*.js')
        .pipe(mocha())
        .pipe(istanbul.writeReports())
        .on('end', cb);
    });
```
That snippet will not run the `.on('finish')` and doesn't seem to even cover the files. I'm using gulp-istanbul 0.5.0 and it isn't working with Gulp 4.0.

**Comment by ilanbiala** [comment]
@SBoudrias any ideas on what's going on?

**Comment by ilanbiala** [comment]
@SBoudrias thoughts?

**Comment by ilanbiala** [comment]
@SBoudrias do you have any idea as to what is going on? I need to run some stuff before mocha and it's done through Gulp, so I can't get coverage right now without this plugin.

**Comment by SBoudrias** [comment]
@ilanbiala I don't have the time to look at it right now. There's roughly 100 lines of code in this plugin, I'm pretty sure you can debug it and maybe send a PR.

**Comment by ilanbiala** [comment]
@SBoudrias did some debugging and looked at the code and tests, but couldn't figure out why task silently fails with gulp-istanbul in the pipe chain...My thoughts are that it has to do with the end of the file and `cover` and the callback for the events. Thoughts?

**Comment by ilanbiala** [comment]
@SBoudrias why did you ask if it was working in 0.3? I'm not understanding whether you are referring to Gulp-istanbul or to Gulp 3.0?

**Comment by SBoudrias** [comment]
@ilanbiala I meant with Gulp 3, so you can make sure it is really related to an issue with Gulp 4.

**Comment by ilanbiala** [comment]
Okay, that makes more sense. Yes it did work with Gulp 3, no it does not work anymore with Gulp 4. I'm not really sure what to investigate specifically in the code because I worked on it as much as I code, and I didn't get any errors or other signs like that.

**Comment by ilanbiala** [comment]
@SBoudrias is there a specific part of the code I should look at?

**Comment by ilanbiala** [comment]
@SBoudrias have you been able to find any parts of the code that look suspicious?

**Comment by ilanbiala** [comment]
@SBoudrias you should at least throw an error in this case because then tests would fail instead of just not running and tricking CI into thinking it's all fine and dandy.

**Comment by ilanbiala** [comment]
@SBoudrias still having this issue with gulp-istanbul 0.6.0 by the way.

**Comment by ilanbiala** [comment]
Any thoughts?

**Comment by SBoudrias** [comment]
If this is urgent for you, fix it yourself.

I honestly don't plan to start debugging an unpublished/unfinished version of Gulp any time soon. Maybe in a couple months if I'm not busy with more important OSS stuff.

**Comment by afloyd** [comment]
I can confirm gulp-istanbul 0.10.3 is working on mac/linux machines. However, not on a windows 8.1 machine... Exact same code works fine on Windows with gulp 3.9.1, but not with the current gulp 4.0 branch.

Everything "seems" to be running fine with windows, but the generated reports don't seem to show that any of the tests run hit any of the instrumented code except for object definitions.

**Comment by ilanbiala** [comment]
@SBoudrias why not just add other OSes to Travis testing?

**Comment by SBoudrias** [comment]
Gulp 4 is not released yet, I honestly don't have time to support and keep up to date with versions who're not released/stable.

**Comment by gbahamondez** [comment]
@SBoudrias  may be this should be closed  in base of this sample? https://github.com/sindresorhus/gulp-mocha/issues/74

**Comment by ilanbiala** [comment]
Yes, it seems a new version of Gulp and dependency updates fix this issue.
