### ISSUE TITLE
Enforce thresholds feature

### ISSUE THREAD

**Issue by peterjwest** [SBoudrias/gulp-istanbul#58]
Would you mind if I make a PR to add threshold enforcing support?

Istanbul has this feature but unfortunately the logic is embedded within a [console command](https://github.com/gotwarlost/istanbul/blob/master/lib/command/check-coverage.js#L157-L180) which only reads from a coverage file.

I imagined it would look like this:

    .pipe(mocha())
    .pipe(istanbul.writeReports())
    .pipe(istanbul.enforceThresholds(thresholds))
    .on('end', cb);

All this would do is check the coverage against thresholds, output a short message and then create a plugin error if the coverage failed.

**Comment by SBoudrias** [comment]
Hey, that is a great idea! It would be pretty useful, feel free to send a PR.
