### ISSUE TITLE
Generators Unexpected token

### ISSUE THREAD

**Issue by albertorestifo** [SBoudrias/gulp-istanbul#60]
The running fails on generators. The issue is with this script and not with Istanbul.

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Unable to parse /{censored}.js

Line 38: Unexpected token *

npm ERR! Test failed.  See above for more details.
```

**Comment by albertorestifo** [comment]
Woops, now noticed the Harmony branch. It works with it.

Thank branch could need some love though

**Comment by SBoudrias** [comment]
You should only provide a ES6 instrumenter: https://github.com/SBoudrias/gulp-istanbul#instrumenter

The harmony branch is pretty dead.

**Comment by albertorestifo** [comment]
Thanks for the additional feedback! Can you suggest me one?

**Comment by albertorestifo** [comment]
Considering I'm having issues with Isparta asking me to use a polyfill, otherwise I get an error `ReferenceError: regeneratorRuntime is not defined`.

Using a polyfill for code my compiler (iojs) supports? NOPE. I'm having no isses with the harmony branch, I will stick to it
