### ISSUE TITLE
Coverage reports not generated when tests fail

### ISSUE THREAD

**Issue by sunjay** [SBoudrias/gulp-istanbul#63]
Here's my gulp task:

	  gulp.task(taskName, function(callback) {
	    require('babel/register')({
	      stage: 0
	    });
	    
	    gulp.src(filesToCover)
	      .pipe(istanbul({
		instrumenter: isparta.Instrumenter,
		includeUntested: true,
		babel: {
		  stage: 0
		}
	      }))
	      .pipe(istanbul.hookRequire())
	      .on('finish', function() {
		gulp.src(testFiles, {read: false})
		  .pipe(mocha({
		    reporter: reporter
		  }))
		  .pipe(istanbul.writeReports())
		  .pipe(istanbul.enforceThresholds({
		    thresholds: {
		      global: minimumCodeCoverage
		    }
		  }))
		  .on('error', function(error) {
		    throw new Error("Code coverage is below " + minimumCodeCoverage + "%");
		  })
		  .on('end', callback);
	      });
	  });

When tests fail, the mocha task throws an error and coverage reports aren't generated. Is there a way to fix this?

Thanks

**Comment by SBoudrias** [comment]
This is not related to gulp-istanbul. If gulp exit because there's an error, gulp-istanbul report task just won't run.

**Comment by sunjay** [comment]
Is there any way to work around this limitation?

**Comment by sunjay** [comment]
Actually, I retract my question. Now that I think about it, this behaviour isn't desirable because coverage would be way off because of all the tests that don't run when mocha fails. 

Thanks
