### ISSUE TITLE
how to call writeReport with a coverage.json file

### ISSUE THREAD

**Issue by skarfacegc** [SBoudrias/gulp-istanbul#64]
I have my code coverage being measured in the browser, and I'm writing the contents of the coverage variable to disk.  how can I pass that coverage file into writeReport so that the coverage report is generated?  

Ideally, how would I combine the browser coverage with the node coverage reports?

**Comment by skarfacegc** [comment]
nevermind.  Took me a bit of digging, but I realized all I needed to do was put a coverage*.json file in the default coverage directory.  I had it named something odd.

**Comment by ashleyconnor** [comment]
Do you have an example of your task?

**Comment by skarfacegc** [comment]
@ashleyconnor  
here's what I ended up with.  also take a look at the view_test task

https://github.com/skarfacegc/FlowTrack2/blob/master/gulpfile.js#L292

**Comment by ashleyconnor** [comment]
Awesome. Thanks @skarfacegc

**Comment by skarfacegc** [comment]
@ashleyconnor glad it helped.  Feel free to ping me with any questions
