### ISSUE TITLE
No report with mocha and istanbul

### ISSUE THREAD

**Issue by iGitScor** [SBoudrias/gulp-istanbul#66]
I have a problem with the integration of gulp-istanbul with gulp-mocha.
The report indicates that the feature is not covered.

[This gist](https://gist.github.com/iGitScor/ca2d76f353a903124441) show you the test file and the script file. They are not in the same directory

If you need more information, please feel free to ask

**Comment by SBoudrias** [comment]
Please use StackOverflow for support questions.

**Comment by iGitScor** [comment]
Two options :
* All the plugin works so your doc is incomplete
* The plugin does'nt work well

So this issue is opened to fix this problem. Do you really think that with StackOverflow I'll find a solution for this specific problem ?

**Comment by SBoudrias** [comment]
Yes, I use these two plugins daily and they've been working fine. I believe it's an issue on your side.
