### ISSUE TITLE
Anti-gulp API

### ISSUE THREAD

**Issue by phated** [SBoudrias/gulp-istanbul#71]
This module breaks many of the gulp plugin contracts and leads people to create poorly structured tasks.

Nesting a stream inside an `on('finish')` is an antipattern and giant red flag that things are being done incorrectly.  Why is the hookRequire method even part of a stream?

Streams should be returned from the gulp task.  By nesting the stream inside the event callback, you are unable to return that stream pipeline.  You can use the callback as per the example but you lose a bunch of internal stuff that gulp does, like sink the stream, etc.

**Comment by SBoudrias** [comment]
Hey, I understand you though this would be helpful, but if you think we're doing it wrong, then please suggest the gulp workflow you'd like to see.

We're open to changes, but you need to let us know what it is you envision.

**Comment by phated** [comment]
Having a single pipeline instead of 2 separate ones (maybe using gulp-if or gulp-filter) would go a long way.  Updating examples to return the streams would too.  I don't have availability to QA all modules and usually just throw them on the blacklist when they are causing multiple issues to be brought up on the main gulp repo.
