### ISSUE TITLE
How to test .es6 files

### ISSUE THREAD

**Issue by vekexasia** [SBoudrias/gulp-istanbul#73]
Hello there,

i'm unsure what i'm doing wrong but with this code

```javascript
gulp.src([dir+'/lib/**.js'])
        .pipe(istanbul({
          instrumenter: isparta.Instrumenter,
        }))
        .pipe(istanbul.hookRequire())
        .on('finish', function() {
          gulp.src([dir+'/test/**/*.es6'], {read: false})


              .pipe(mocha({reporter: 'dot'}))
              .pipe(istanbul.writeReports({
                dir: coverageDir,
                reportOpts: {dir: coverageDir},
                reporters: ['text', 'text-summary', 'json', 'html']
              }))
              .on('end', cb);
        });
```

I get the code coverage working but if i change the first `gulp.src(` to use .es6 (obviously renaming also the files in the folder from *.js to *.es6) i don't get it working at all.

I tried to understand what's wrong but i honestly wasn't able to understand if the problem is with gulp-istanbul, istanbul or babel :(

**Comment by SBoudrias** [comment]
My guess is a tool somewhere is not catching `.es6` files as being valid javascript.

This also raise the question of why you're using a non standard extension for JavaScript files?

**Comment by vekexasia** [comment]
i wanted to separate es5 and es6 files. isn't it a good pattern?

**Comment by SBoudrias** [comment]
JavaScript is just JavaScript, you shouldn't separate them. Babel won't break if it parses an es5 file.

**Comment by vekexasia** [comment]
ok then. 'll use .js then. :) you can close the issue :)
