### ISSUE TITLE
Add Hook Class: hookRunInThisContext 

### ISSUE THREAD

**Issue by danieljoppi** [SBoudrias/gulp-istanbul#75]
I need this hook to my project [nsmockup](https://github.com/suiteplus/nsmockup).

I am using vm.runInThisContext to import my JS files in node.js

``` javascript
var fs = require('fs'),
    vm = require('vm'),
    vmInclude = function(code, path) {
        vm.runInThisContext(code, path);
    },
    vmAddFile = function(path) {
        vmInclude(fs.readFileSync(path), path);
    };
```

I can't use require in this project :(

**Comment by SBoudrias** [comment]
Can you explain more the "why" of this requirement?

**Comment by SBoudrias** [comment]
That being said, I won't have an issue merging the PR. It's part of the istanbul API, so it just make sense we expose it here too.

I'm just curious about the context of this requirement.

**Comment by danieljoppi** [comment]
Because in my project I can not use the require('') ... I'm making this API to simplify test automation in Netsuite ERP system.

So I have to respect the Netsuite ERP system conditions ... and so I need to include my scripts in VM.
