### ISSUE TITLE
Syntax errors break watched tasks

### ISSUE THREAD

**Issue by erbridge** [SBoudrias/gulp-istanbul#77]
My gulpfile:

```js
gulp.task('pre-test', function preTestTask() {
  return gulp.src(srcPaths)
    .pipe(istanbul({
      includeUntested: true,
    }))
    .pipe(istanbul.hookRequire());
});

gulp.task('test', [ 'pre-test' ], function testTask() {
  return gulp.src(testPaths)
    .pipe(plumber())
    .pipe(mocha())
    .pipe(istanbul.writeReports());
});

gulp.task('watch-test', [ 'test' ], function watchTestTask() {
  return gulp.watch(srcPaths.concat(testPaths), [ 'test' ]);
});
```

Running `gulp watch-test` behaves as expected until a syntax error is encountered. On further changes, only the `pre-test` task is run. Commenting out `.pipe(istanbul.writeReports())` fixes things (but obviously without the coverage reports).

**Comment by SBoudrias** [comment]
When there's errors, we send them on the pipe. It's up to you to catch and ignore them.

**Comment by erbridge** [comment]
My understanding is that that's what `gulp-plumber` is supposed to do. What's strange is that the `pre-test` task is run on subsequent saves, but not the main `test` task. Perhaps I'm not understanding how this stuff works...
