### ISSUE TITLE
Support 'file' option for reporters

### ISSUE THREAD

**Issue by jreichenberg** [SBoudrias/gulp-istanbul#79]
Many istanbul reporters (ex. cobertura) take 'file' as an option in addition to 'dir'. gulp-istanbul currently only passes 'dir' through in the reporter opts via:

```
reportOpts: { dir: opts.dir || defaultDir }
```

if this is changed to 

```
reportOpts: { dir: opts.dir || defaultDir, file: opts.file }
```

multiple runs of gulp-istanbul can create individual report files in the same dir without overwriting.

**Comment by SBoudrias** [comment]
Send a PR ;)
