### ISSUE TITLE
CSS (?) issue in HTML reports

### ISSUE THREAD

**Issue by kamek-pf** [SBoudrias/gulp-istanbul#80]
Hey,

Just noticed the progress bar is messed up in HTML reports (see pic related).
![screenshot from 2015-10-20 22-41-27](https://cloud.githubusercontent.com/assets/3883992/10626338/e31bb0d0-777b-11e5-897a-c6400651f6e4.png)
 src/ has 100% code coverage, yet the bar isn't fully filled.

Not sure if I had to report this here or on the istanbul repo, but this doesn't happen with vanilla istanbul.

**Comment by SBoudrias** [comment]
We're not doing any special handling. Report this on the istanbul repo.
