### ISSUE TITLE
README example incorrect?

### ISSUE THREAD

**Issue by ashleyconnor** [SBoudrias/gulp-istanbul#89]
If I add this task to my `gulpfile.js` - I get no output in my `test-tmp`.

```
gulp.task('pre-test', function () {
  return gulp.src(['lib/**/*.js'])
    // Covering files
    .pipe(istanbul())
    // Force `require` to return covered files
    .pipe(istanbul.hookRequire())
    // Write the covered files to a temporary directory
    .pipe(gulp.dest('test-tmp/'));
});
```

However removing this line `.pipe(istanbul.hookRequire())` - I get the instrumented files output in the `test-tmp` folder.

**Comment by SBoudrias** [comment]
Oh yeah, you wouldn't need to `hookRequire` at all in this case.
