### ISSUE TITLE
if includeUntested is true, why file.path is resolved ?

### ISSUE THREAD

**Issue by nimrod-becker** [SBoudrias/gulp-istanbul#90]
Line 53
` global[opts.coverageVariable][path.resolve(file.path)] = covStub;`

Why is path resolved for the file.path incase includeUntested is supplied ? Why isn't file.path simply used ?

Thanks!

**Comment by SBoudrias** [comment]
`path.resolve()` just enforce the path to be fully qualified. It probably should always resolved before usage.

**Comment by nimrod-becker** [comment]
Not exactly a bug, was just wandering. Since usually the files are passed via .src or something similar.

In my specific case, I'm having several tests (can be divided according to type: unit tests and system tests which are run under different paths. I'm adjusting the paths so that the final report can be an aggregation of the various runs, and resolving the path make them two different sources thus two coverage reports per single file.

**Comment by SBoudrias** [comment]
@nimrod-becker maybe it's safe to remove the line. Feel free to test it out and if everything looks fine, then send a PR.
