### ISSUE TITLE
Strange behavior/return code when used with mocha "after" hook

### ISSUE THREAD

**Issue by treythomas123** [SBoudrias/gulp-istanbul#93]
I'm seeing some strange behavior with gulp-mocha and gulp-istanbul, and have created a simple project with just the following two files to try to narrow down the issue:

**gulpfile.js**
```js
const gulp = require('gulp');
const istanbul = require('gulp-istanbul');
const mocha = require('gulp-mocha');

gulp.task('test', ['pre-test'], () =>
    gulp.src('test.js')
        .pipe(mocha())
        //.on('error', err => console.log(err) )
        .pipe(istanbul.writeReports())
);

gulp.task('pre-test', () =>
    gulp.src('lib/**/*.js')
        .pipe(istanbul())
);
```

**test.js**
```js
describe('something', function() {
    it('should work', function() {
        throw new Error('fail');
    });
});

after( function() {
    console.log('after');
});
```

I would expect `gulp test` to fail and return a non-zero exit code. Instead, I see the following output, with return code 0:
```
[11:20:02] Using gulpfile ~/temp/gulpfile.js
[11:20:02] Starting 'pre-test'...
[11:20:02] Finished 'pre-test' after 13 ms
[11:20:02] Starting 'test'...


  something
    1) should work

after

  0 passing (6ms)
  1 failing

  1) something should work:
     Error: fail
      at Context.<anonymous> (test.js:3:15)



  2) "after all" hook
```
Everything in the output looks fine up til that last line: `2) "after all" hook`

Now, if I comment out either the `after` hook in `test.js`, or the `.pipe(istanbul.writeReports())` line in `gulpfile.js`, the output looks fine and I get return code 1:

**without `after` hook**
```
[11:28:08] Using gulpfile ~/temp/gulpfile.js
[11:28:08] Starting 'pre-test'...
[11:28:08] Finished 'pre-test' after 14 ms
[11:28:08] Starting 'test'...


  something
    1) should work


  0 passing (5ms)
  1 failing

  1) something should work:
     Error: fail
      at Context.<anonymous> (test.js:3:15)




events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: 1 test failed.
```

**without pipe to istanbul.writeReports**
```
[11:26:54] Using gulpfile ~/temp/gulpfile.js
[11:26:54] Starting 'pre-test'...
[11:26:54] Finished 'pre-test' after 12 ms
[11:26:54] Starting 'test'...


  something
    1) should work

after

  0 passing (7ms)
  1 failing

  1) something should work:
     Error: fail
      at Context.<anonymous> (test.js:3:15)



[11:26:54] 'test' errored after 21 ms
[11:26:54] Error in plugin 'gulp-mocha'
Message:
    1 test failed.
```

So it seems like something about the combination of a mocha `after` hook, and `istanbul.writeReports` is causing problems. At first I thought this was likely a `gulp-mocha` issue, but then I tried adding an `on('error')` handler (commented out in the gulpfile code above), and the error event emitted by gulp-mocha seems correct.

I'll try to debug this further when I have some time, but I thought I'd post an issue in case anyone else is seeing this.

Versions I'm using:
```
├── gulp@3.9.1
├── gulp-istanbul@0.10.4
├── gulp-mocha@2.2.0
└── istanbul@0.4.3
```

**Comment by SBoudrias** [comment]
`after` should go inside the describe blocks.

Anyway, that's not a bug related to gulp-istanbul, it's mocha related.

**Comment by treythomas123** [comment]
You can put `after` hooks at the root level and they'll run after all tests. See [Root-Level Hooks](https://mochajs.org/#hooks) section in mocha docs.

It could very well be a mocha or gulp-mocha issue, but it works fine when I use those without gulp-istanbul.

**Comment by treythomas123** [comment]
This seems to be an issue with gulp-mocha or maybe mocha, since I tried piping to `gulp.dest` instead of gulp-istanbul and I see the same behavior.

Wrote a [gulp-mocha](https://github.com/sindresorhus/gulp-mocha/issues/129) issue for this.
